"""Added google_book_id and review fields

Revision ID: edb8b4e66342
Revises: b3ea056105f5
Create Date: 2023-09-21 16:45:29.018155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb8b4e66342'
down_revision = 'b3ea056105f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_book_id', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint('uq_google_book_id', ['google_book_id'])


    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('text')
        batch_op.drop_column('rating')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_book_id')

    # ### end Alembic commands ###
